apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: server
  namespace: otterize-tutorial-iam
spec:
  service:
    name: server
  calls:
    - name: arn:aws:s3:::<S3 Bucket Name>/*
      type: aws
      awsActions:
        - "s3:PutObject"
