apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-spiffe
  namespace: cert-manager
spec:
  isCA: true
  duration: 87660h # 10 years
  secretName: cert-manager-spiffe
  commonName: cert-manager-spiffe.mattiasgees.be
  subject:
    organizations:
    - mattiasgees
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-spiffe
spec:
  ca:
    secretName: cert-manager-spiffe
